apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: omarpfe/projectpfe:latest  # Utiliser l'image Docker Hub
        ports:
        - containerPort: 8083  # Port d'écoute du conteneur (Spring Boot)
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  ports:
  - port: 8083       # Port d'exposition du service
    targetPort: 8083  # Port dans le conteneur
    nodePort: 30083   # Port externe pour accéder à l'application
  selector:
    app: spring-boot-app
