apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: thourayalouati/devopsimage23  # Votre image Docker
        ports:
        - containerPort: 9091  # Port d'écoute de l'application Spring Boot dans le conteneur
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  ports:
  - port: 9091       # Port d'exposition du service
    targetPort: 9091  # Le port dans le conteneur
    nodePort: 30091   # Port externe pour accéder à l'application (peut être différent si nécessaire)
  selector:
    app: spring-boot-app
